# Site settings
title: 
email: maximilian.voecklinghaus@teacher.rahn.education
description: >-
  Mathematik, Informatik & interaktives Lernen
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Header pages (navigation)
header_pages:
  - about.md
  - teaching.md

# Social links
github_username: maxvoeck
linkedin_username: dein-linkedin

